In [22]:
import pandas as pd
import numpy as np

In [2]:
url="https://www.statista.com/statistics/188910/us-music-album-sales-by-genre-2010/"

In [3]:
dataframe1=pd.io.html.read_html(url)

In [4]:
dataframe1[1]

             Unnamed: 0    2008    2009    2010    2011   2012   2013   2014
0   Christian / Gospel*   29.79   27.82   24.23   23.73   22.9  19.53  17.36
1               Country   47.66   46.13   43.72   42.92   44.6  36.46  30.46
2    Dance / Electronic       -       -    8.74   10.05    8.7   7.11   5.26
3                 Latin   25.13    16.5   12.35   11.81    9.7   8.27   6.26
4                   R&B   77.01   69.89   57.87   55.44   49.7  47.78  35.75
5                  Rock  139.67  124.16  103.71  105.69  102.5  92.93  85.25
6                   Pop       -       -       -       -      -  24.62  27.71
7           Alternative   80.92    68.2   53.73   55.03   52.2      -      -
8             Classical   13.32   12.14    8.96    9.57    7.5      -      -
9                  Jazz   11.79   11.78    8.78   11.08    8.1      -      -
10                Metal   50.48   38.73   32.55   32.21   31.9      -      -
11              New Age    2.94    2.35    1.66    1.93    1.7      -      -
12                  Rap   33.41   26.44   27.33   28.25   24.2      -      -
13           Soundtrack   20.85   18.98   16.41   13.23   12.3      -      -

In [8]:
music_data=dataframe1[1].iloc[:,0:5]

In [10]:
music_data.columns=["Genre","2008","2009","2010","2011"]

In [17]:
music_data=music_data.drop([6])

In [23]:
music_data.replace("-",np.nan)

                  Genre    2008    2009    2010    2011
0   Christian / Gospel*   29.79   27.82   24.23   23.73
1               Country   47.66   46.13   43.72   42.92
2    Dance / Electronic     NaN     NaN    8.74   10.05
3                 Latin   25.13    16.5   12.35   11.81
4                   R&B   77.01   69.89   57.87   55.44
5                  Rock  139.67  124.16  103.71  105.69
7           Alternative   80.92    68.2   53.73   55.03
8             Classical   13.32   12.14    8.96    9.57
9                  Jazz   11.79   11.78    8.78   11.08
10                Metal   50.48   38.73   32.55   32.21
11              New Age    2.94    2.35    1.66    1.93
12                  Rap   33.41   26.44   27.33   28.25
13           Soundtrack   20.85   18.98   16.41   13.23

In [24]:
music_data.to_csv("assignment3_music_data_ryotaro.csv")